### ISSUE TITLE
PA speed control

### ISSUE THREAD

**Issue by DeputyLOL** [Crzyrndm/Pilot-Assistant#18] opened 2015-12-19 19:42 UTC
I think it would be useful for PA to remember your speed settings when you load a craft. I know its a little thing but it would be very handy. Maybe just make it so that speed setting can be saved in presets.
By speed settings I mean IAS, EAS, TAS and knots, m/s, etc...

Also, I noticed that PAs speed control stopped working with RPM after the speed update. 
Is that RPMs problem? 

Lastly, there is an inconsistency between the 3 mods that I use that show me airspeed 
(PA, FAR, RPM). I know that's not PAs fault but I was wondering if there would be an easy way to match the IAS in PA with the IAS in RPM and FAR (both in knots). If no then that's fine, ill try and figure a way round it.

**Comment by DeputyLOL** [comment] 2015-12-19 20:00
Also, why does direct throttle input have a speed setting? :3

**Comment by Crzyrndm** [comment] 2015-12-20 03:14
"Also, why does direct throttle input have a speed setting? :3"
* If it says speed somewhere, that'd be a typo.
* Adding the speed settings to the presets is probably a good idea.
* The inconsistency is something I know about but haven't been able to locate the cause of since I copied it almost line for line from FAR. It's pending investigation
* I wasn't aware the RPM had implemented any compatibility so I'm not entirely sure of the details. I did have a conversation with MoarDV somewhere about it but I can't seem to locate it. I don't think I've changed the function signatures since then though so I don't know what's happening there

**Comment by DeputyLOL** [comment] 2015-12-20 20:55
I can change the throttle % into IAS, TAS or EAS and change its unit. If I set it to knots than 100% becomes 50ish%. you shouldn't be able to change that in the direct throttle control.

**Comment by Crzyrndm** [comment] 2015-12-20 21:50
https://i.imgur.com/iWKad22.jpg
Yea, that shouldn't be happening...

**Comment by DeputyLOL** [comment] 2015-12-21 17:04
are you considering impletementing some of the features of kramax autopilot?
such as the waypoint navigation?

**Comment by Crzyrndm** [comment] 2015-12-21 19:00
I will not be. The level of Automation used in Kramax is beyond the scope I have for PA

**Comment by DeputyLOL** [comment] 2015-12-21 23:36
Aww...

**Comment by DeputyLOL** [comment] 2015-12-28 21:44
when I use RPM to input numbers into the speed control, if set to anything other than m/s the numbers change don't match the number inputted.

Probably something to do with the conversion into different units.

**Comment by Crzyrndm** [comment] 2015-12-28 22:54
Most likely, RPM isn't aware of the speed settings and all speed inputs are being treated as m/s

**Comment by DeputyLOL** [comment] 2015-12-28 23:36
is there any fix?
I also notice that when not set to m/s, the speed control is a bit buggy. When engaging, it will target a speed different from your current speed and x and z don't change by 100 intervals.

**Comment by Crzyrndm** [comment] 2015-12-29 04:06
I'll have a poke at the engaging issue, hotkeys I can just about guarantee are still working in m/s

**Comment by DeputyLOL** [comment] 2015-12-29 13:34
X and z do change the speed but not in 100 intervals.

**Comment by Crzyrndm** [comment] 2015-12-29 21:39
What I meant was that if you switch back to m/s, the intervals will be 100's still, they're just transformed by the conversion factor. Regardless, I've just fixed the missing conversion

**Comment by DeputyLOL** [comment] 2016-01-01 20:06
![image](https://cloud.githubusercontent.com/assets/12616126/12072008/fa1a0b58-b0c2-11e5-907d-343bbb239023.png)
The conversion between RPM is still off a bit but it looks like it is slightly better

**Comment by DeputyLOL** [comment] 2016-01-01 20:50
Looking back, the gap has actually got bigger....
But the RPM to PA transfer works and matches.

**Comment by Crzyrndm** [comment] 2016-01-01 20:52
TAS / IAS / EAS ?

**Comment by DeputyLOL** [comment] 2016-01-01 20:52
IAS

**Comment by DeputyLOL** [comment] 2016-01-01 20:53
in knots

**Comment by DeputyLOL** [comment] 2016-01-01 20:55
This is what I'm working on in RPM to narrow the gap.


RPM_MAPPED_VARIABLE
{
  sourceVariable = ALTITUDE
  sourceRange = 100,10000
  mappedVariable = PA_SPEEDINPUT_ALTITUDE
  mappedRange = 479,493.6
}

RPM_MAPPED_VARIABLE
{
  sourceVariable = PERSISTENT_MCP_SpeedInput
  sourceRange = 0,500
  mappedVariable = PA_SPEEDINPUT
  mappedRange = 0,MAPPED_PA_SPEEDINPUT_ALTITUDE
}

//	        PA RPM 
//100m   - 500 (522)
//100m   - 200 (208.8)
//10000m - 500 (506.4)
//10000m - 200 (202.7)

**Comment by DeputyLOL** [comment] 2016-01-01 20:57
At the bottom is a little table that shows what PA was showing and RPM was showing at different heights

**Comment by Crzyrndm** [comment] 2016-01-01 22:06
Alright, the difference is how atmospheric density is being calculated. If you fly to ~45 degrees N/S on Kerbin, the differences will disappear because that is the value used by FAR/RPM. My understanding of this would be that neither has updated the method to account for the thermal system which causes the atmospheric density to vary between the polar and equatorial regions (they use a constant density for a given altitude).

**Comment by DeputyLOL** [comment] 2016-01-01 22:10
ahhhh... will you keep it as it is or will you change it to fit the other mods?

**Comment by Crzyrndm** [comment] 2016-01-01 22:10
I'll poke FAR and see what the expert has to say :P

**Comment by DeputyLOL** [comment] 2016-01-01 22:11
It says there are new extension for RPM on the releases page, anything new working with RPM?

**Comment by Crzyrndm** [comment] 2016-01-01 22:15
not until RPM adds support for them. I did notify MoarDv of the changes [here](https://github.com/Crzyrndm/Pilot-Assistant/issues/15)

**Comment by DeputyLOL** [comment] 2016-01-02 14:58
Do you think you could expose the green number next to the heading in RPM?
I'm working on a flight director system that tells how to manually fly what you've entered into the autopilot.
I am completely stumped on the heading part as it goes from 360 to 1. If I could use the number from PA or at least know how to get to it, I could finish a big section of the horizontal flight director.

**Comment by Crzyrndm** [comment] 2016-01-02 23:05
The green number is just a little math.

targetDelta = target - current;
if (targetDelta < -180) targetDelta += 360;
if (targetDelta > 180) targetDelta -= 360;

**Comment by Crzyrndm** [comment] 2016-01-02 23:05
The green number is just a little math.

targetDelta = target - current;
if (targetDelta < -180) targetDelta += 360;
if (targetDelta > 180) targetDelta -= 360;

**Comment by DeputyLOL** [comment] 2016-01-02 23:54
ok thanks, ill try and reproduce that in RPM

**Comment by DeputyLOL** [comment] 2016-01-04 01:25
I got the roll section done. I'm stumped on how to do the pitch though because there is so many variables.
I noticed that FAR has made a dev build with the updated IAS. Have you asked MoarDv about RPM yet?

**Comment by Crzyrndm** [comment] 2016-01-04 02:18
Waiting to see how FARs numbers line up, the earlier commit was a little [off](https://github.com/ferram4/Ferram-Aerospace-Research/issues/121#issuecomment-168564545)

**Comment by Crzyrndm** [comment] 2016-01-08 01:50
FAR matches, RPM has acknowledged the issue as a bug. Closing this

**Closed by Crzyrndm** 2016-01-08 01:50 UTC
